config/routes.rb
LabMarks::Application.routes.draw do

  resources :marks
  resources :sheets
  resources :assessments
  resources :experiments
  resources :students
  resources :markers
  resources :sessions, :only => [:new, :create, :destroy]

  resources :students do
    collection { post :import }
  end

  root  'pages#home'

  match '/signup',  	to: 'markers#new',      via: 'get'
  match '/signin',  	to: 'sessions#new',     via: 'get'
  match '/signout', 	to: 'sessions#destroy', via: 'delete'
  match '/help',    	to: 'pages#help',       via: 'get'
  match '/about',   	to: 'pages#about',      via: 'get'
  match '/statistics',  to: 'pages#statistics', via: 'get'
  match '/contact', 	to: 'pages#contact',    via: 'get'
  match '/marklist', 	to: 'pages#marklist',   via: 'get'
  match '/upload', 	to: 'pages#upload',     via: 'get'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  get "pages/statistics"
  get "pages/marklist"
  get "pages/upload"

  

end

app/models/assessment.rb
# == Schema Information
#
# Table name: assessments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  value      :integer
#  desc       :text
#  created_at :datetime
#  updated_at :datetime
#

class Assessment < ActiveRecord::Base
  attr_accessible :name, :value, :desc

  has_many :marks
  has_many :sheets, through: :marks
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  def index
    @title = "List Assessments"
    @assessments = Assessment.all
  end

  def show
    @title = "Show Assessment"
    @assessment = Assessment.find(params[:id])
  end

  def new
    @title = "New Assessment"
    @assessment = Assessment.new
  end

  def create
    @assessment = Assessment.new(params[:assessment])
    if @assessment.save
      redirect_to @assessment, :notice => "Successfully created assessment."
    else
      render :action => 'new'
    end
  end

  def edit
    @title = "Edit Assessment"
    @assessment = Assessment.find(params[:id])
  end

  def update
    @assessment = Assessment.find(params[:id])
    if @assessment.update_attributes(params[:assessment])
      redirect_to @assessment, :notice  => "Successfully updated assessment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @assessment = Assessment.find(params[:id])
    @assessment.destroy
    redirect_to assessments_url, :notice => "Successfully destroyed assessment."
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<%= form_for @assessment do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/assessments/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @assessment %> |
  <%= link_to "View All", assessments_path %>
</p>

app/views/assessments/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th>Desc</th>
  </tr>
  <% for assessment in @assessments %>
    <tr>
      <td><%= assessment.name %></td>
      <td><%= assessment.value %></td>
      <td><%= assessment.desc %></td>
      <td><%= link_to "Show", assessment %></td>
      <td><%= link_to "Edit", edit_assessment_path(assessment) %></td>
      <td><%= link_to "Destroy", assessment, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Assessment", new_assessment_path %></p>

app/views/assessments/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back to List", assessments_path %></p>

app/views/assessments/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @assessment.name %>
</p>
<p>
  <strong>Value:</strong>
  <%= @assessment.value %>
</p>
<p>
  <strong>Desc:</strong>
  <%= @assessment.desc %>
</p>

<p>
  <%= link_to "Edit", edit_assessment_path(@assessment) %> |
  <%= link_to "Destroy", @assessment, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", assessments_path %>
</p>