config/routes.rb
LabMarks::Application.routes.draw do

  resources :marks
  resources :sheets
  resources :assessments
  resources :experiments
  resources :students
  resources :markers
  resources :sessions, :only => [:new, :create, :destroy]

  resources :students do
    collection { post :import }
  end

  root  'pages#home'

  match '/signup',  	to: 'markers#new',      via: 'get'
  match '/signin',  	to: 'sessions#new',     via: 'get'
  match '/signout', 	to: 'sessions#destroy', via: 'delete'
  match '/help',    	to: 'pages#help',       via: 'get'
  match '/about',   	to: 'pages#about',      via: 'get'
  match '/statistics',  to: 'pages#statistics', via: 'get'
  match '/contact', 	to: 'pages#contact',    via: 'get'
  match '/marklist', 	to: 'pages#marklist',   via: 'get'
  match '/upload', 	to: 'pages#upload',     via: 'get'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  get "pages/statistics"
  get "pages/marklist"
  get "pages/upload"

  

end

app/models/marker.rb
# == Schema Information
#
# Table name: markers
#
#  id                 :integer          not null, primary key
#  first              :string(255)
#  last               :string(255)
#  email              :string(255)
#  abbr               :string(255)
#  scaling            :float
#  admin              :boolean
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class Marker < ActiveRecord::Base

  attr_accessor :password  # create virtual attribute 'password'

  attr_accessible :first, :last, :email, :abbr, :scaling, 
                  :admin, :password, :password_confirmation

  has_many :sheets

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first, :presence => true,
                    :length   => { :maximum => 32 }
  validates :last, :presence => true,
                    :length   => { :maximum => 32 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :abbr, :presence => true, uniqueness: true

  validates :scaling, numericality: {greater_than_or_equal_to: 0}

  # automatically create a virtual attribute 'password_confirmation'

  validates :password, :presence	=> true,
                       :confirmation	=> true,
                       :length		=> { :minimum => 6 }, on: :create

  before_update :check_password

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    marker = find_by_email(email)
    return nil if marker.nil?
    return marker if marker.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    marker = find_by_id(id)
    (marker && marker.salt == cookie_salt) ? marker : nil
  end

  def name
    self.last + ',  ' + self.first
  end

  private

    def encrypt_password

      # need to use 'self' here because we're ASSIGNING an 
      # object attribute - otherwise all that will happen is a
      # local variable called encrypted_password would be created.

      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

    def check_password
      is_ok = self.password.nil? || 
              self.password.empty? || 
              self.password.length >= 6

      self.errors[:password] << "Password is too short (minimum is 6 characters)" unless is_ok

      is_ok # return Boolean indicating success; if it fails, save is blocked
    end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :new, :destroy, :index]
  before_filter :correct_marker, :only => [:show]
  helper_method :sort_column, :sort_direction

  def index
    @title = "List Markers"
    @markers = Marker.order("last ASC")
  end


  def show
    @title = "Show Marker"
    @marker = Marker.find(params[:id])
    @sheets = @marker.sheets.paginate(:page => params[:page],
             :per_page => 10).all( 
             :joins => [:experiment, :student],
             :order => "#{sort_column} #{sort_direction}")

  end

  def new
    @title = "New Marker"
    @marker = Marker.new
  end

  def create
    @marker = Marker.new(params[:marker])
    if @marker.save
      # handle a successful save 
      redirect_to markers_path, :notice => "Successfully created marker."
    else
      @title = "New Marker"
      render 'new'
    end
  end

  def edit
    @title = "Edit Marker"
    @marker = Marker.find(params[:id])
  end

  def update
    @marker = Marker.find(params[:id])
    if @marker.update_attributes(params[:marker])
#      redirect_to @marker, :notice  => "Successfully updated marker."
      redirect_to :back, :notice  => "Successfully updated marker."
    else
      render :action => 'edit'
    end
  end


  def destroy
    @marker = Marker.find(params[:id])
    @marker.destroy
    redirect_to markers_url, :notice => "Successfully destroyed marker."
  end

private

  def authenticate
    deny_access unless signed_in? && is_admin?
  end

  def correct_marker
    @marker = Marker.find(params[:id])
    redirect_to(root_path) unless ( current_marker?(@marker) || is_admin? )
  end

  def sort_column
    cols = Sheet.column_names + Experiment.column_names + Student.column_names
    cols.include?(params[:sort]) ? params[:sort] : "last"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/markers/_form-no-pass.html.erb
<%= form_for @marker do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first, "First Name(s)" %><br />
    <%= f.text_field :first %>
  </p>
  <p>
    <%= f.label :last, "Last Name" %><br />
    <%= f.text_field :last %>
  </p>
  <p>
    <%= f.label :email, "Email" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :abbr, "Abbreviation" %><br />
    <%= f.text_field :abbr %>
  </p>
  <p>
    <%= f.label :scaling, "Scaling Factor" %><br />
    <%= f.text_field :scaling %>
  </p>
  <p>
  <%= f.check_box :admin %><%= f.label(:admin, "Administrator?") %>
  </p>
  <p>
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/markers/_form.html.erb
<%= form_for @marker, :html => { :class => "form-horizontal" } do |f| %>

  <%= render 'shared/error_messages', :object => f.object  %>

  <fieldset>
  <legend>Create/Edit Marker</legend>
    <div class="control-group">
    <%= f.label :first, "First Name(s)", class: "control-label" %>
    <div class="controls">
    <%= f.text_field :first %>
    </div>
    </div>
    <div class="control-group">
    <%= f.label :last, "Last Name", class: "control-label" %>
    <div class="controls">
    <%= f.text_field :last %>
    </div>
    </div>
    <div class="control-group">
    <%= f.label :email, "Email", class: "control-label" %>
    <div class="controls">
    <%= f.text_field :email %>
    </div>
    </div>
    <div class="control-group">
    <%= f.label :abbr, "Abbreviation", class: "control-label" %>
    <div class="controls">
    <%= f.text_field :abbr %>
    </div>
    </div>

    <div class="control-group">
    <%= f.label :admin, "Administrator?", class: "control-label" %>
    <div class="controls">
    <%= f.check_box :admin %>
    </div>
    </div>
    <div class="control-group">
    <%= f.label :password, "Password", class: "control-label" %>
    <div class="controls">
    <%= f.password_field :password %>
    </div>
    </div>
    <div class="control-group">
    <%= f.label :password_confirmation, "Password Confirmation", class: "control-label" %>
    <div class="controls">
    <%= f.password_field :password_confirmation %>
    </div>
    </div>

    <%= f.hidden_field :scaling, value: 1.0 %>

    <div class="form-actions">
    <%= f.submit class: "btn btn-primary btn-xs"%>
    </div>
</fieldset>
<% end %>

app/views/markers/edit.html.erb
<%= render 'form' %>

<p><%= link_to "Back", :back, class: "btn btn-primary btn-sm" %></p>

app/views/markers/index.html.erb
<h1>Markers</h1>
<table class="table table-condensed table-striped">
  <tr>
    <th>Abbr</th>
    <th>Name</th>
    <th># Sheets</th>
    <th>Email</th>
    <th>Scaling</th>
    <th>Admin</th>
    <th colspan="3">Actions</th>
  </tr>
  <% for marker in @markers %>
    <tr>
      <td><%= marker.abbr %></td>
      <td><%= "#{marker.last},#{marker.first}" %></td>
      <td><%= marker.sheets.count %></td>
      <td><%= marker.email %></td>
      <td><%= marker.scaling %></td>
      <td><%= marker.admin ? "Yes" : "No" %></td>
      <td><%= link_to "Show", marker,
              :class => "btn btn-success btn-xs" %></td>
      <td><%= link_to "Edit", edit_marker_path(marker),
              :class => "btn btn-warning btn-xs" %></td>
      <td><%= link_to "Destroy", marker, 
              :confirm => 'Are you sure?', 
              :method => :delete,
              :class => "btn btn-danger btn-xs" %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Marker", new_marker_path,
       :class => "btn btn-primary btn-xs" %></p>

app/views/markers/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back", :back, class: "btn btn-primary btn-xs" %></p>

app/views/markers/show.html.erb
<h3><%= "#{@marker.first} #{@marker.last}" %></h3>
<p>
    <b>EMail: </b><%= @marker.email %>
    &nbsp;&nbsp;&nbsp;
    <b>Abbreviation: </b><%= @marker.abbr %>
    &nbsp;&nbsp;&nbsp;

<% if @sheets.empty? %>
  You have not yet created any mark sheets.

<% else %>

<b>Completed mark sheets: </b><%=@marker.sheets.size%>
</p>
<%= will_paginate @sheets %>
<table class="table table-condensed table-striped table-hover table-responsive">
  <tr>
    <th><%= sortable "last", "Student" %></th>
    <th>Partner</th>
    <th><%= sortable "title", "Experiment" %></th>
    <th><%= sortable "updated_at", "Updated" %></th>
    <th>Total</th>
    <th>Ret(%)</th>
    <th colspan="3">Actions</th>
  </tr>
  <% for sheet in @sheets %>
    <tr>
      <td><%= truncate("#{sheet.student.last},#{sheet.student.first}",
              length: 20, separator: ' ')%></td>
      <td><%= truncate("#{sheet.partner.last},#{sheet.partner.first}",
              length: 20, separator: ' ')%></td>
      <td><%= sheet.experiment.title %></td>
      <td><%= sheet.updated_at %></td>
      <td style="text-align:center;"><%= sheet.total_mark %></td>
      <td style="text-align:center;"><%= (100 * sheet.return_mark).to_i %></td>
      <td><%= link_to "Show", sheet,
              :class => 'btn btn-success btn-xs' %></td>
      <td><%= link_to "Edit", edit_sheet_path(sheet),
              :class => 'btn btn-warning btn-xs' %></td>
      </td>
      <td><% if is_admin? %>
        <%= link_to "Destroy", sheet, 
            :confirm => 'Are you sure?', 
            :method => :delete, :class => 'btn btn-danger btn-xs' %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

<% end %>

<p><%= link_to "Create New Mark Sheet", new_sheet_path,
               :class => 'btn btn-primary btn-xs' %></p>