config/routes.rb
LabMarks::Application.routes.draw do

  resources :marks
  resources :sheets
  resources :assessments
  resources :experiments
  resources :students
  resources :markers
  resources :sessions, :only => [:new, :create, :destroy]

  resources :students do
    collection { post :import }
  end

  root  'pages#home'

  match '/signup',  	to: 'markers#new',      via: 'get'
  match '/signin',  	to: 'sessions#new',     via: 'get'
  match '/signout', 	to: 'sessions#destroy', via: 'delete'
  match '/help',    	to: 'pages#help',       via: 'get'
  match '/about',   	to: 'pages#about',      via: 'get'
  match '/statistics',  to: 'pages#statistics', via: 'get'
  match '/contact', 	to: 'pages#contact',    via: 'get'
  match '/marklist', 	to: 'pages#marklist',   via: 'get'
  match '/upload', 	to: 'pages#upload',     via: 'get'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  get "pages/statistics"
  get "pages/marklist"
  get "pages/upload"

  

end

app/models/experiment.rb
# == Schema Information
#
# Table name: experiments
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  desc       :text
#  created_at :datetime
#  updated_at :datetime
#

class Experiment < ActiveRecord::Base
  attr_accessible :title, :desc
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  before_filter :authenticate

  def index
    @title = "List Experiments"
    @experiments = Experiment.all
  end

  def show
    @title = "Show Experiment"
    @experiment = Experiment.find(params[:id])
  end

  def new
    @title = "New Experiment"
    @experiment = Experiment.new
  end

  def create
    @experiment = Experiment.new(params[:experiment])
    if @experiment.save
      redirect_to @experiment, :notice => "Successfully created experiment."
    else
      render :action => 'new'
    end
  end

  def edit
    @title = "Edit Experiment"
    @experiment = Experiment.find(params[:id])
  end

  def update
    @experiment = Experiment.find(params[:id])
    if @experiment.update_attributes(params[:experiment])
      redirect_to @experiment, :notice  => "Successfully updated experiment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @experiment = Experiment.find(params[:id])
    @experiment.destroy
    redirect_to experiments_url, :notice => "Successfully destroyed experiment."
  end

private

  def authenticate
    deny_access unless signed_in? && is_admin?
  end

end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for @experiment do |f| %>
  <%= render 'shared/error_messages', :object => f.object  %>
  <fieldset>
  <legend>Create/Edit Experiment</legend>
    <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls">
    <%= f.text_field :title %>
    </div>
    </div>
    <div class="control-group">
    <%= f.label :desc, "Description", class: "control-label" %>
    <div class="controls">
    <%= f.text_area :desc %>
    </div>
    </div>
    <div class="form-actions">
    <%= f.submit class: "btn btn-primary btn-xs" %>
    </div>
  </fieldset>

<% end %>

app/views/experiments/edit.html.erb
<%= render 'form' %>
<p><%= link_to "Back", :back, class: "btn btn-primary btn-sm" %></p>

app/views/experiments/index.html.erb
<h1>Experiments</h1>
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3">Actions</th>
  </tr>
  <% for experiment in @experiments %>
    <tr>
      <td><%= experiment.title %></td>
      <td><%= experiment.desc %></td>
      <td><%= link_to "Show", experiment,
              :class => "btn btn-success btn-xs"%></td>
      <td><%= link_to "Edit", edit_experiment_path(experiment),
              :class => "btn btn-warning btn-xs"%></td>
      <td><%= link_to "Destroy", experiment, 
              :confirm => 'Are you sure?', 
              :method => :delete,
              :class => "btn btn-danger btn-xs"%></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Experiment", new_experiment_path,
       :class => 'btn btn-primary btn-xs' %></p>

app/views/experiments/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back", :back, class: "btn btn-primary btn-sm" %></p>

app/views/experiments/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @experiment.title %>
</p>
<p>
  <strong>Desc:</strong>
  <%= @experiment.desc %>
</p>

<p>
  <%= link_to "Edit", edit_experiment_path(@experiment) %> |
  <%= link_to "Destroy", @experiment, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to "View All", experiments_path %>
</p>