config/routes.rb
LabMarks::Application.routes.draw do

  resources :marks
  resources :sheets
  resources :assessments
  resources :experiments
  resources :students
  resources :markers
  resources :sessions, :only => [:new, :create, :destroy]

  resources :students do
    collection { post :import }
  end

  root  'pages#home'

  match '/signup',  	to: 'markers#new',      via: 'get'
  match '/signin',  	to: 'sessions#new',     via: 'get'
  match '/signout', 	to: 'sessions#destroy', via: 'delete'
  match '/help',    	to: 'pages#help',       via: 'get'
  match '/about',   	to: 'pages#about',      via: 'get'
  match '/statistics',  to: 'pages#statistics', via: 'get'
  match '/contact', 	to: 'pages#contact',    via: 'get'
  match '/marklist', 	to: 'pages#marklist',   via: 'get'
  match '/upload', 	to: 'pages#upload',     via: 'get'

  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  get "pages/statistics"
  get "pages/marklist"
  get "pages/upload"

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">

  <small>
    LabMarks v0.1 JPH
  </small>
<!--  <nav>
    <% if is_admin? %>
    <ul>
    <li><%= link_to "Mark List",    "/marklist" %></li>
    <li><%= link_to "Statistics",    "/statistics" %></li>
    <li><%= link_to "Experiments",    experiments_path %></li>
    <li><%= link_to "Mark Sheets",    sheets_path %></li>
    <li><%= link_to "Students",    students_path %></li>
    <li><%= link_to "Markers",    markers_path %></li>
    </ul>
    <% else %>
    <ul>
    <li><%= link_to "About",    about_path %></li>
    <li><%= link_to "Contact",    contact_path %></li>
    </ul>
    <% end %>
  </nav> -->
    <%= debug(params) if Rails.env.development? %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to root_path, id: "logo" do %>
        <span style="color:#f00;">Lab</span><span style="color:#66f;">Marks</span>
      <% end %>

      <nav>
    <ul class="nav pull-right">
    <% if signed_in? %>

     <li> <%= link_to "Signed in as #{@current_marker.first} #{@current_marker.last}",  current_marker %></li>

      <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_marker %></li>
                <li><%= link_to "Help",    help_path %></li>
                <li><%= link_to "About",    about_path %></li>
    <% if is_admin? %>
                <li class="divider"></li>
    <li><%= link_to "Mark List",    "/marklist" %></li>
    <li><%= link_to "Statistics",    "/statistics" %></li>
    <li><%= link_to "Experiments",    experiments_path %></li>
    <li><%= link_to "Mark Sheets",    sheets_path %></li>
    <li><%= link_to "Students",    students_path %></li>
    <li><%= link_to "Markers",    markers_path %></li>
    <li><%= link_to "Data Upload",    upload_path %></li>
    <% end %>

                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
    <% else %>
      <li><%= link_to "Home",    root_path %></li>
      <li><%= link_to "About",    about_path %></li>
    <% end %>
    <% unless signed_in? %>
      <li><%= link_to "Sign in", signin_path %></li>
    <% end %>

    </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |key,value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>